<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <maxConcurrentInstances>1</maxConcurrentInstances>
   <numberOfRerun>3</numberOfRerun>
   <orchestration>CLASSIC</orchestration>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>922cdc57-55b6-4021-a240-bc4d2c67e392</testSuiteGuid>
   <testCaseLink>
      <guid>ce9fd1ba-cbab-4c67-87dd-2622439c4c71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>28efdb52-c0d7-4156-8ae5-42109e116575</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login_data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>28efdb52-c0d7-4156-8ae5-42109e116575</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>033f675a-9793-4595-af25-2b2155774ee3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>28efdb52-c0d7-4156-8ae5-42109e116575</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b2c8246e-0f51-4af0-9238-31da7137518a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
