<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Sort</name>
   <tag></tag>
   <elementGuidId>5817393c-a820-4252-b31b-e3dfb0a67913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@class='product_sort_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@class='product_sort_container']</value>
      <webElementGuid>d2306182-b339-4d4e-9239-48988743a638</webElementGuid>
   </webElementProperties>
</WebElementEntity>
